### PR TITLE
Enable nullable

### PR DESCRIPTION
**Pull request by Mbucari**
I've been on a quest to enable nullable reference types. I found the best way to do this is to enable one file at a time so the warnings aren't as overwhelming.

I also changed a few things:

- Use the built-in .NET `HashCode` struct to generate hash codes
- Remove Enum `GetValues<T>` extensions. They're built-in to .NET
- Change enum generic constraints from `struct, IConvertible` to `struct, Enum`
- Change `EnsureGreaterThan` and `EnsureBetweenInclusive` generic constraints from `IComparable<T>` to `struct, INumber<T>`

### CODE REVIEW

**Comment by rmcrackan** [comment]
I hate to do this to you after all that effort, but I really don't want this library to enable that flag. In fact, seeing all of that extra code required is why.

> Use the built-in .NET HashCode struct to generate hash codes
> Remove Enum GetValues<T> extensions. They're built-in to .NET
> Change enum generic constraints from struct, IConvertible to struct, Enum
> Change EnsureGreaterThan and EnsureBetweenInclusive generic constraints from IComparable<T> to struct, INumber<T>

These sound reasonable.

**Comment by Mbucari** [comment]
> I really don't want this library to enable that flag

OK. Then can I at least enable file-level nullable in some places? Some of these are really useful, like

`public static T EnsureNotNull<T>([NotNull] T? argument, string name)`

When called from a nullable context, the compiler know that after it returns argument will not be null.

Also things like this:
```
[return: NotNullIfNotNull(nameof(str))]
public static string? Truncate(this string? str, int limit)
```
When called from a nullable context the compiler knows that if `str` is not null then it returns a non-null value.

> In fact, seeing all of that extra code required is why.

I'm just not seeing much in the way of "extra" code. For the most part it's just marking reference types as nullable. When I added more than that it's because the existing code was assuming that variables were not null when there was no basis for that assumption.

For example in `ObjectExtensions.getDescription`, the call to `GetMember()` was using a nullable string, but `GetMember` doesn't accept nullable strings so I changed it to make sure the string had a value first. If  the argument was null it would have thrown an exception. Cases like what are the whole point of nullable contexts: make all your nullity assumptions explicit you you can prevent NREs

EDIT* Another example of "extra" code that's a good idea is in `BasicStep`. `public Func<bool> Fn` has a public setter so it could be null at any time, but `RunRaw()` was not doing a null check before invoking it.

**Comment by rmcrackan** [comment]
`[NotNull]` on inputs is the same as saying 'if null then throw argument null exception', right? Sure, I have no problem with that.

> I'm just not seeing much in the way of "extra" code.

It's death by 1,000 cuts. With that flag turned on, the code has to be littered with `?` to avoid the complier warnings/errors. I too wish the C# team had made better decisions on day 1 about nulls, but they didn't and I'm just not enamored with their attempts to try to fix it, incl. the nullable flag.

**Comment by Mbucari** [comment]
All of these changes have absolutely no effect on users of this library unless the user's code has also enabled nullable. Given that, can I keep most/all of these changes but just remove the project-level nullable and enable it in each file? That way any future additions would have nullable disabled by default.

**Comment by rmcrackan** [comment]
> All of these changes have absolutely no effect on users of this library unless the user's code has also enabled nullable.

Yeah, except that I am also a user :) 

Sure, if you leave the project level flags off, do as you like with things like attributes. Here's what I don't want: the project flag is on and then anytime I create a reference type, I have to stop what I'm doing to make the compiler happy with little decorators. Attributes are on code that *you* choose to edit. `<Nullable>` is on all future code.

**Comment by Mbucari** [comment]
All right, It's done. Thanks for not making me throw it all away lol.

I agree it's not _pretty_, but I like the coding patterns it forces me into.

**Pull request merged**
